=== minghui2019/QUICKTOOLKIT/src/main/resource/dtd/Field.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % Category SYSTEM "Category.dtd">
%Category;
<!ELEMENT Fields (Field+)>
<!ELEMENT Field (fieldId, fieldName, dataType, categoryName|Category?, precision?, joinColumn?, AppendSearch?, genericity?, orderBy?, fetch?)>
<!ATTLIST Field
		association (OneToMany|ManyToOne) #IMPLIED
		onlyMeta (true|false) "false"
		ignoreImport (true|false) "false"
		updateInsert (true|false) "true"
		tranSient (true|false) "true">
<!ELEMENT fieldId (#PCDATA)>
<!ELEMENT fieldName (#PCDATA)>
<!ELEMENT dataType (#PCDATA)>
<!ELEMENT categoryName (#PCDATA)>
<!--<!ELEMENT Category (#PCDATA)>-->
<!--<!ATTLIST Category-->
<!--	name CDATA #REQUIRED-->
<!--	note CDATA #REQUIRED-->
<!--	type (人员|项目|成果|系统|平台|系统图表|学术交流|评审|经费|合同|考核|系统参数|个人空间|财务同步|编号生成) #REQUIRED>-->
<!ELEMENT precision (#PCDATA)>
<!ELEMENT joinColumn (#PCDATA)>
<!ELEMENT AppendSearch (value)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST AppendSearch
		relativeField CDATA #REQUIRED
		relativeThisProperty CDATA "id"
		searchValLabel (val) #IMPLIED
		mergeMultiVals (true|false) "false"
		symbol CDATA ",">
<!ELEMENT genericity (#PCDATA)>
<!ELEMENT orderBy (#PCDATA)>
<!ELEMENT fetch (#PCDATA)>

=== minghui2019/QUICKTOOLKIT/src/main/resource/field/Field172403.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Fields SYSTEM '../dtd/Field.dtd'>
<Fields>
	<Field>
		<fieldId>centerDirector</fieldId>
		<fieldName>中心主任</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>centerDirectorId</fieldId>
		<fieldName>中心主任ID</fieldName>
		<dataType>String</dataType>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>centerDeputyDirector</fieldId>
		<fieldName>中心副主任</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>centerDeputyDirectorId</fieldId>
		<fieldName>中心副主任ID</fieldName>
		<dataType>String</dataType>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>instituteLeaders</fieldId>
		<fieldName>分管副院长</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>instituteLeadersId</fieldId>
		<fieldName>分管副院长ID</fieldName>
		<dataType>String</dataType>
		<precision>32</precision>
	</Field>
	<!-- <Field>
		<fieldId>relyOnPatentsPatentee</fieldId>
		<fieldName>AIRS是否为第一专利权人</fieldName>
		<dataType>String</dataType>
		<precision>500</precision>
	</Field>
	<Field>
		<fieldId>patentSource</fieldId>
		<fieldName>专利来源</fieldName>
		<dataType>String</dataType>
		<categoryName>PATENT_SOURCE</categoryName>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>transferor</fieldId>
		<fieldName>转让单位</fieldName>
		<dataType>String</dataType>
		<precision>500</precision>
	</Field>
	<Field>
		<fieldId>country</fieldId>
		<fieldName>国别</fieldName>
		<dataType>String</dataType>
		<precision>200</precision>
	</Field>
	<Field>
		<fieldId>agencyContactPerson</fieldId>
		<fieldName>代理机构联系人</fieldName>
		<dataType>String</dataType>
		<precision>100</precision>
	</Field>
	<Field>
		<fieldId>agencyContactNumber</fieldId>
		<fieldName>代理机构联系人电话</fieldName>
		<dataType>String</dataType>
		<precision>32</precision>
	</Field> -->
	<!-- 
	<Field>
		<fieldId>contractQuantity</fieldId>
		<fieldName>合同数量</fieldName>
		<dataType>Integer</dataType>
		<TranSient>true</TranSient>
		<AppendSearch relativeField="BUYER_NAME" relativeThisProperty="name">
			<value>SELECT BUYER_NAME, COUNT(BUYER_NAME) val FROM BIZ_YF_CONTRACT WHERE BUYER_NAME IN (^{name}) GROUP BY BUYER_NAME</value>
		</AppendSearch>
	</Field>
	<Field>
		<fieldId>fundingType</fieldId>
		<fieldName>资助类型</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>fundingCategory</fieldId>
		<fieldName>资助类别</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>researchDirection</fieldId>
		<fieldName>研究方向</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>contactNumber</fieldId>
		<fieldName>联系电话</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>email</fieldId>
		<fieldName>电子信箱</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	 -->
	<!-- <Field>
		<fieldId>birthDay</fieldId>
		<fieldName>出生年月</fieldName>
		<dataType>Date</dataType>
	</Field>
	<Field>
		<fieldId>executivePost</fieldId>
		<fieldName>行政职务</fieldName>
		<dataType>String</dataType>
		<categoryName>EXECUTIVE_POST</categoryName>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>contactName</fieldId>
		<fieldName>联系人姓名</fieldName>
		<dataType>String</dataType>
		<precision>100</precision>
	</Field>
	<Field>
		<fieldId>contactPhone</fieldId>
		<fieldName>联系人手机</fieldName>
		<dataType>String</dataType>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>contactEmail</fieldId>
		<fieldName>联系人邮箱</fieldName>
		<dataType>String</dataType>
		<precision>100</precision>
	</Field> -->
	<!-- <Field>
		<fieldId>reviewResult</fieldId>
		<fieldName>评审结果</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>reviewInfo</fieldId>
		<fieldName>评审建议</fieldName>
		<dataType>String</dataType>
		<precision>1024</precision>
	</Field>
	<Field>
		<fieldId>reviewMark</fieldId>
		<fieldName>评审分值</fieldName>
		<dataType>Double</dataType>
	</Field>
	<Field>
		<fieldId>expertReviewId</fieldId>
		<fieldName>专家评审id</fieldName>
		<dataType>String</dataType>
		<TranSient>true</TranSient>
	</Field>
	<Field>
		<fieldId>expertJsonBySubjectId</fieldId>
		<fieldName>系统学科对应的专家信息</fieldName>
		<dataType>JSONArray</dataType>
		<TranSient>true</TranSient>
	</Field>
	<Field>
		<fieldId>subjectExpert</fieldId>
		<fieldName>学科专家</fieldName>
		<dataType>String</dataType>
		<TranSient>true</TranSient>
	</Field>
	<Field>
		<fieldId>schedule</fieldId>
		<fieldName>评审进度</fieldName>
		<dataType>Double</dataType>
		<TranSient>true</TranSient>
	</Field>
	<Field>
		<fieldId>scheduleMessage</fieldId>
		<fieldName>评审进度显示信息</fieldName>
		<dataType>String</dataType>
		<TranSient>true</TranSient>
	</Field>
	<Field>
		<fieldId>reviewExpertJson</fieldId>
		<fieldName>组装评审专家json</fieldName>
		<dataType>JSONArray</dataType>
		<TranSient>true</TranSient>
	</Field>
	<Field>
		<fieldId>reviewExpert</fieldId>
		<fieldName>评审专家</fieldName>
		<dataType>String</dataType>
		<TranSient>true</TranSient>
	</Field>
	<Field>
		<fieldId>memberPersonIds</fieldId>
		<fieldName>成员personId</fieldName>
		<dataType>String</dataType>
		<TranSient>true</TranSient>
	</Field>
	<Field>
		<fieldId>memberNames</fieldId>
		<fieldName>专利成员</fieldName>
		<dataType>String</dataType>
		<TranSient>true</TranSient>
	</Field> -->
	<!-- <Field>
		<fieldId>projectId</fieldId>
		<fieldName>所属项目ID</fieldName>
		<dataType>String</dataType>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>relyOnExistingPatents</fieldId>
		<fieldName>是否依赖现有专利进行申请</fieldName>
		<dataType>String</dataType>
		<categoryName>SF</categoryName>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>relyOnPatentsPatentee</fieldId>
		<fieldName>AIRS是否是依赖专利的专利权人</fieldName>
		<dataType>String</dataType>
		<categoryName>SF</categoryName>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>technicalField</fieldId>
		<fieldName>所属技术领域</fieldName>
		<dataType>String</dataType>
		<precision>500</precision>
	</Field>
	<Field>
		<fieldId>technicalDisclosureAuthor</fieldId>
		<fieldName>技术交底书撰写人</fieldName>
		<dataType>String</dataType>
		<precision>500</precision>
	</Field>
	<Field>
		<fieldId>referenceDocumentAnnex</fieldId>
		<fieldName>对比文件附件</fieldName>
		<dataType>String</dataType>
		<precision>500</precision>
	</Field>
	<Field>
		<fieldId>technicalContactName</fieldId>
		<fieldName>技术问题联系人姓名</fieldName>
		<dataType>String</dataType>
		<precision>500</precision>
	</Field>
	<Field>
		<fieldId>technicalContactPhone</fieldId>
		<fieldName>技术问题联系人电话</fieldName>
		<dataType>String</dataType>
		<precision>32</precision>
	</Field>
	<Field>
		<fieldId>technicalContactEmail</fieldId>
		<fieldName>技术问题联系人邮件</fieldName>
		<dataType>String</dataType>
		<precision>50</precision>
	</Field>
	<Field>
		<fieldId>technicalBackground</fieldId>
		<fieldName>技术背景</fieldName>
		<dataType>String</dataType>
		<precision>2000</precision>
	</Field>
	<Field>
		<fieldId>technicalProblem</fieldId>
		<fieldName>现有技术不足及存在问题</fieldName>
		<dataType>String</dataType>
		<precision>2000</precision>
	</Field>
	<Field>
		<fieldId>technicalSolutions</fieldId>
		<fieldName>技术方案</fieldName>
		<dataType>String</dataType>
		<precision>100</precision>
	</Field>
	<Field>
		<fieldId>technicaleffect</fieldId>
		<fieldName>技术效果</fieldName>
		<dataType>String</dataType>
		<precision>100</precision>
	</Field>
	<Field>
		<fieldId>searchResultsAnalysis</fieldId>
		<fieldName>检索结果及分析</fieldName>
		<dataType>String</dataType>
		<precision>2000</precision>
	</Field>
	<Field>
		<fieldId>creativity</fieldId>
		<fieldName>创造性</fieldName>
		<dataType>String</dataType>
		<precision>2000</precision>
	</Field>
	<Field>
		<fieldId>technicalBarriers</fieldId>
		<fieldName>技术壁垒</fieldName>
		<dataType>String</dataType>
		<precision>2000</precision>
	</Field>
	<Field>
		<fieldId>beingInfringed</fieldId>
		<fieldName>被侵权的易发现性和易取证性</fieldName>
		<dataType>String</dataType>
		<precision>2000</precision>
	</Field> -->
	
</Fields>
