=== minghui2019/QUICKTOOLKIT/src/main/resource/dtd/ModuleView.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT ModuleViews (ModuleView+)>
        <!ELEMENT ModuleView (beanId, tableName, sheetName?, viewName, described)>
        <!-- 是否忽略 -->
        <!ATTLIST ModuleView ignore (true|false) "false">
        <!-- 模块英文名称 -->
        <!ELEMENT beanId (#PCDATA)>
        <!-- 表格名称 -->
        <!ELEMENT tableName (#PCDATA)>
        <!-- 表格名称 -->
        <!ELEMENT sheetName (#PCDATA)>
        <!-- 视图名称 -->
        <!ELEMENT viewName (#PCDATA)>
        <!-- 模块中文名称 -->
        <!ELEMENT described (#PCDATA)>

=== minghui2019/QUICKTOOLKIT/src/main/resource/view/ModuleView.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModuleViews SYSTEM "../dtd/ModuleView.dtd">

<ModuleViews>
    <ModuleView ignore="false">
        <beanId>yfContract</beanId>
        <tableName>BIZ_YF_CONTRACT</tableName>
        <viewName>V_KY_HXXM</viewName>
        <checkStatus>2</checkStatus>
        <described>横向项目</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>yfContractMember</beanId>
        <tableName>BIZ_YF_CONTRACT_MEMBER</tableName>
        <viewName>V_KY_HXXM_RY</viewName>
        <described>横向项目成员</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>xJProject</beanId>
        <tableName>BIZ_XJ_PROJECT</tableName>
        <viewName>V_KY_XJXM</viewName>
        <checkStatus>2</checkStatus>
        <described>校级项目</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>xJProjectMember</beanId>
        <tableName>BIZ_XJ_PROJECT_MEMBER</tableName>
        <viewName>V_KY_XJXM_RY</viewName>
        <described>校级项目成员</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>zXProject</beanId>
        <tableName>BIZ_ZX_PROJECT</tableName>
        <viewName>V_KY_ZXXM</viewName>
        <checkStatus>2</checkStatus>
        <described>纵向项目</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>zXProjectMember</beanId>
        <tableName>BIZ_ZX_PROJECT_MEMBER</tableName>
        <viewName>V_KY_ZXXM_RY</viewName>
        <described>纵向项目成员</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>zXProjectCooperationUnit</beanId>
        <tableName>BIZ_PROJECT_COOPERATION_UNIT</tableName>
        <viewName>V_KY_XM_XZDW</viewName>
        <described>科研项目协作单位</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>inSchoolSubject</beanId>
        <tableName>BIZ_PROJECT_IN_SCHOOL</tableName>
        <viewName>V_KY_XM_ZKT</viewName>
        <described>校内子课题信息</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>projectBudgetFee</beanId>
        <tableName>BIZ_PROJECT_BUDGET_FEE</tableName>
        <viewName>V_KY_XM_JFYS</viewName>
        <described>项目经费预算信息</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>projectIncome</beanId>
        <tableName>BIZ_PROJECT_INCOME</tableName>
        <viewName>V_KY_XM_JFDZ</viewName>
        <checkStatus>2</checkStatus>
        <described>经费到账</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>cWIncomeClaim</beanId>
        <tableName>BIZ_CW_INCOME_CLAIM</tableName>
        <viewName>V_KY_XM_JFRL</viewName>
        <checkStatus>2</checkStatus>
        <described>经费认领</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>cWIncomeClaim</beanId>
        <tableName>BIZ_CW_INCOME_CLAIM</tableName>
        <viewName>V_KY_XM_ZKT_JFRL</viewName>
        <checkStatus>2</checkStatus>
        <described>子课题经费认领</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>projectPayoutDetail</beanId>
        <tableName>BIZ_PROJECT_PAYOUT_DETAIL</tableName>
        <viewName>V_KY_XM_JFZC</viewName>
        <described>经费报销明细</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>assessResultDetail</beanId>
        <tableName>KH_RESULT_DETAILS</tableName>
        <viewName>V_KY_KHMX</viewName>
        <described>科研成果考核明细</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>meeting</beanId>
        <tableName>BIZ_MEETING</tableName>
        <viewName>V_KY_XSHY</viewName>
        <checkStatus>2</checkStatus>
        <described>主办会议</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>personnelAccept</beanId>
        <tableName>BIZ_PERSONNEL_ACCEPT</tableName>
        <viewName>V_KY_XSJLJSRY</viewName>
        <checkStatus>2</checkStatus>
        <described>人员接受</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>personnelDispatch</beanId>
        <tableName>BIZ_PERSONNEL_DISPATCH</tableName>
        <viewName>V_KY_XSJLPCRY</viewName>
        <checkStatus>2</checkStatus>
        <described>人员派遣</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>lecture</beanId>
        <tableName>BIZ_LECTURE</tableName>
        <viewName>V_KY_XSBG</viewName>
        <checkStatus>2</checkStatus>
        <described>学术报告</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>paper</beanId>
        <tableName>BIZ_PAPER</tableName>
        <viewName>V_KY_LW</viewName>
        <checkStatus>2</checkStatus>
        <described>论文</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>magazine</beanId>
        <tableName>DM_MAGAZINE</tableName>
        <viewName>V_KY_LW_QKYXYZ</viewName>
        <described>期刊信息</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>paperInclude</beanId>
        <tableName>BIZ_PAPER_INCLUDE</tableName>
        <viewName>V_KY_LW_SL</viewName>
        <described>论文收录</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>paperReship</beanId>
        <tableName>BIZ_PAPER_RESHIP</tableName>
        <viewName>V_KY_LW_ZZ</viewName>
        <described>论文转载</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>paperAuthor</beanId>
        <tableName>BIZ_PAPER_AUTHOR</tableName>
        <viewName>V_KY_LW_RY</viewName>
        <described>论文作者</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>book</beanId>
        <tableName>BIZ_BOOK</tableName>
        <viewName>V_KY_ZZ</viewName>
        <checkStatus>2</checkStatus>
        <described>著作</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>bookAuthor</beanId>
        <tableName>BIZ_BOOK_AUTHOR</tableName>
        <viewName>V_KY_ZZ_RY</viewName>
        <described>著作作者</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>patent</beanId>
        <tableName>BIZ_PATENT</tableName>
        <viewName>V_KY_ZL</viewName>
        <checkStatus>2</checkStatus>
        <described>专利成果</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>patentAuthor</beanId>
        <tableName>BIZ_PATENT_AUTHOR</tableName>
        <viewName>V_KY_ZL_RY</viewName>
        <described>专利成果作者</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>honor</beanId>
        <tableName>BIZ_HONOR</tableName>
        <viewName>V_KY_CGHJ</viewName>
        <checkStatus>2</checkStatus>
        <described>获奖</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>honorAuthor</beanId>
        <tableName>BIZ_HONOR_AUTHOR</tableName>
        <viewName>V_KY_CGHJ_RY</viewName>
        <described>获奖完成人</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>jdProduct</beanId>
        <tableName>BIZ_APPRAISAL_PRODUCT</tableName>
        <viewName>V_KY_CGJD</viewName>
        <checkStatus>2</checkStatus>
        <described>鉴定成果</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>jdProductAuthor</beanId>
        <tableName>BIZ_APPRAISAL_PRODUCT_AUTHOR</tableName>
        <viewName>V_KY_CGJD_RY</viewName>
        <described>鉴定成果作者</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>copyRight</beanId>
        <tableName>BIZ_COPYRIGHT</tableName>
        <viewName>V_KY_ZZQ</viewName>
        <checkStatus>2</checkStatus>
        <described>著作权</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>copyRightAuthor</beanId>
        <tableName>BIZ_COPYRIGHT_AUTHOR</tableName>
        <viewName>V_KY_ZZQ_RY</viewName>
        <described>著作权作者</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>researchReport</beanId>
        <tableName>BIZ_RESEARCH_REPORT</tableName>
        <viewName>V_KY_ZXBG</viewName>
        <checkStatus>2</checkStatus>
        <described>研究与咨询报告</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>researchReportAuthor</beanId>
        <tableName>BIZ_RESEARCH_REPORT_AUTHOR</tableName>
        <viewName>V_KY_ZXBG_RY</viewName>
        <described>研究与咨询报告作者</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>standard</beanId>
        <tableName>BIZ_STANDARD</tableName>
        <viewName>V_KY_BZ</viewName>
        <checkStatus>2</checkStatus>
        <described>标准</described>
    </ModuleView>
    <ModuleView ignore="false">
        <beanId>standardAuthor</beanId>
        <tableName>BIZ_STANDARD_AUTHOR</tableName>
        <viewName>V_KY_BZ_RY</viewName>
        <described>标准作者</described>
    </ModuleView>
</ModuleViews>
